import { expect, test } from '@playwright/test'
import path from 'node:path'
import { expectImported, keyboardChooseSelect, startUI, tabTo, writeSkillFixture } from './helpers'

test('keyboard-only Add Source, Import, Assignment, Distribution, destructive confirm, and focus restore', async ({ page }) => {
  const ui = await startUI()
  try {
    await page.goto(ui.url + '/setup')
    await expect(page.getByRole('heading', { name: 'Welcome to Skill Manager' })).toBeVisible()
    await tabTo(page, page.getByRole('button', { name: 'Initialize' }))
    await page.keyboard.press('Enter')
    await expect(page.getByRole('heading', { name: 'Skills' })).toBeVisible()

    const sourceRoot = path.join(ui.home, 'upstream')
    writeSkillFixture(sourceRoot, 'keys')

    await tabTo(page, page.getByRole('navigation', { name: 'Main navigation' }).getByRole('link', { name: 'Sources', exact: true }))
    await page.keyboard.press('Enter')
    await tabTo(page, page.getByRole('button', { name: 'Add Source' }))
    await page.keyboard.press('Enter')
    await expect(page.getByRole('dialog')).toBeVisible()
    await tabTo(page, page.getByLabel('Location'))
    await page.keyboard.type(sourceRoot)
    await tabTo(page, page.getByLabel('Name (optional)'))
    await page.keyboard.type('key-src')
    await tabTo(page, page.getByRole('button', { name: 'Register and scan' }))
    await page.keyboard.press('Enter')
    await expect(page.getByRole('heading', { name: 'key-src' })).toBeVisible()
    await tabTo(page, page.getByRole('button', { name: 'Import all' }))
    await page.keyboard.press('Enter')
    await expectImported(page)

    await tabTo(page, page.getByRole('navigation', { name: 'Main navigation' }).getByRole('link', { name: 'Groups', exact: true }))
    await page.keyboard.press('Enter')
    await tabTo(page, page.getByRole('button', { name: 'Create Group' }))
    await page.keyboard.press('Enter')
    await expect(page.getByRole('dialog')).toBeVisible()
    await tabTo(page, page.getByLabel('Group Name'))
    await page.keyboard.type('key-group')
    await tabTo(page, page.getByRole('dialog').getByRole('button', { name: 'Create Group' }))
    await page.keyboard.press('Enter')
    await tabTo(page, page.getByRole('table', { name: 'Managed Groups' }).getByRole('link', { name: 'key-group' }))
    await page.keyboard.press('Enter')
    await expect(page.getByRole('heading', { name: 'key-group' })).toBeVisible()
    await keyboardChooseSelect(page, 'Select a Skill to add', 'keys')
    await tabTo(page, page.getByRole('button', { name: 'Add Skill' }))
    await page.keyboard.press('Enter')

    const deleteBtn = page.getByRole('button', { name: 'Delete' })
    await tabTo(page, deleteBtn)
    await page.keyboard.press('Enter')
    const confirm = page.getByRole('alertdialog')
    await expect(confirm).toBeVisible()
    await expect(confirm.getByRole('button').first()).toBeFocused({ timeout: 3_000 }).catch(async () => {
      await expect(confirm).toBeFocused()
    })
    await page.keyboard.press('Escape')
    await expect(confirm).toHaveCount(0)
    await expect(deleteBtn).toBeFocused()

    const targetDir = path.join(ui.home, 'key-target')
    await tabTo(page, page.getByRole('navigation', { name: 'Main navigation' }).getByRole('link', { name: 'Targets', exact: true }))
    await page.keyboard.press('Enter')
    await tabTo(page, page.getByRole('button', { name: 'Register Target' }))
    await page.keyboard.press('Enter')
    await expect(page.getByRole('dialog')).toBeVisible()
    await keyboardChooseSelect(page, 'Target Type', 'Custom Directory Path')
    await tabTo(page, page.getByLabel('Target Name'))
    await page.keyboard.type('key-tgt')
    await tabTo(page, page.getByLabel('Directory Path'))
    await page.keyboard.type(targetDir)
    await tabTo(page, page.getByRole('dialog').getByRole('button', { name: 'Register Target' }))
    await page.keyboard.press('Enter')
    await tabTo(page, page.getByRole('table', { name: 'Registered Targets' }).getByRole('link', { name: 'key-tgt' }))
    await page.keyboard.press('Enter')
    await expect(page.getByRole('heading', { name: 'key-tgt' })).toBeVisible()
    await keyboardChooseSelect(page, 'Assignment Type', 'Group')
    await keyboardChooseSelect(page, 'Group', 'key-group')
    await expect(page.getByRole('button', { name: 'Assign' })).toBeEnabled()
    await tabTo(page, page.getByRole('button', { name: 'Assign' }))
    await page.keyboard.press('Enter')

    const distribute = page.getByRole('button', { name: 'Distribute' })
    await tabTo(page, distribute)
    await page.keyboard.press('Enter')
    const dialog = page.getByRole('alertdialog')
    await expect(dialog).toBeVisible()
    await expect(dialog.getByRole('button').first()).toBeFocused({ timeout: 3_000 }).catch(async () => {
      await expect(dialog).toBeFocused()
    })
    await page.keyboard.press('Escape')
    await expect(dialog).toHaveCount(0)
    await expect(distribute).toBeFocused()
  } finally {
    await ui.stop()
  }
})
